---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peytz-mail-geo
  namespace: default
  labels:
    app: geoip_database
spec:
  selector:
    matchLabels:
      app: geoip_database
      role: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: geoip_database
        role: backend
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 250m
            memory: 250Mi
        ports:
        - containerPort: 3000
---        
apiVersion: v1
kind: Service
metadata:
  name: peytz-mail-geo
  namespace: default
  labels:
    app: geoip_database
    role: backend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: geoip_database
    role: backend
