swagger: '2.0'
info:
  title: GeoIP API
  description: GeoIP service is a management tool that can be used to get country geo data by client's request IP address.
  contact:
    name: PeytzMail Support
    email: support@peytz.dk
    url: https://peytzmail.com/
  version: 1.0.0
host: 'geo.peytzmail.com'
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
